version: '3'
services:
  web:
    build: ./code/python-flask-server/
    environment:
      - NEO4J_AUTH=none
    ports:
      - "8080:8080"
      - "8071:5000"
    depends_on:
      - "db"
  db:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
      # This sets java's heap size to 1G. If you get java.lang.OutOfMemoryError
      # then you may need to increase this.
      - _JAVA_OPTIONS="-Xmx16g"
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      # NOTE: if docker-compose is run under 'sudo' then $HOME will be 'root'
      # Change path2neo to your local path
      - /Users/srensi/Documents/GitHub/GNBR_api/data/neo4j/data:/data
      - /Users/srensi/Documents/GitHub/GNBR_api/data/neo4j/import:/import
      - /Users/srensi/Documents/GitHub/GNBR_api/data/neo4j/logs:/logs 
